[build]
  command = "npm run build"
  publish = ".next"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  from = '/_next/image/*'
  query = { q = ':quality', url = ':url', w = ':width' }
  to = '/.netlify/images?url=:url&w=:width&q=:quality'
  force = true



  [[plugins]]
  package = "@netlify/plugin-nextjs"



